# Support Python 3.12+.
target-version = "py312"
# Set the maximum line length to 79.
line-length = 79

[lint]
# Add the `line-too-long` rule to the enforced rule set.
extend-select = ["E501"]

[format]
quote-style = "single"
